### ISSUE TITLE
MIrrors

### ISSUE THREAD

**Issue by Dokotela** [dart-lang/dart-docker#103]
Is there any plan to include dart:mirrors in the Dart runtime for Docker in the future? (specifically I'm trying to run Conduit and right now it won't let me). Thankis!

**Comment by athomas** [comment]
dart:mirrors is a feature of the Dart SDK, the Dart docker images include a full Dart SDK. It only works on the native JIT VM, though (https://dart.dev/guides/libraries). So applications using dart:mirrors can't use `dart compile exe` which we generally recommend. However, the Dart SDK included in the docker image could also be used to run regular Dart programs. However, you would not end up with a slim image.

**Comment by athomas** [comment]
This may be more helpful for JIT applications: https://github.com/dart-lang/dart-docker/issues/101#issuecomment-1159140422
