### ISSUE TITLE
Upgrade to Debian bookworm

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dart-docker#161]
bullseye is old - and has unpatched critical vulnerabilities

https://hub.docker.com/layers/library/dart/latest/images/sha256-a154d77a8df7aeac46fdf15edd72f01c03b1b569e1a4c80263c22e1245507d21?context=explore

**Comment by cpswan** [comment]
Dupe of #157

**Comment by cpswan** [comment]
@kevmoo I've updated the title on #157 to make it clearer what needs to be done
