### ISSUE TITLE
Automated tests to confirm availability of images on DockerHub

### ISSUE THREAD

**Issue by cpswan** [dart-lang/dart-docker#182]
There have been numerous instances in the past where publication of images on DockerHub has significantly lagged updates to [`versions.json`](https://github.com/dart-lang/dart-docker/blob/main/versions.json) or where images for an instruction set architecture are missing e.g. #178 #105 #97 #93

A GitHub Actions workflow could confirm that image SHAs exist for expected tags, and a badge could be places on the README.md to indicate that all is well.

**Comment by athomas** [comment]
Hmm, not sure why GH didn't close this issue. The linked PR has landed.
