### ISSUE TITLE
Lag between SDK releases and Dart library image updates (again)

### ISSUE THREAD

**Issue by cpswan** [dart-lang/dart-docker#204]
It's been 6 days since 3.5.1 was released, but the `:latest` build is still at 3.5.0

`versions.json` here was updated with the 3.5.1 hashes in https://github.com/dart-lang/dart-docker/commit/23860711d655df4ce3c6b87d72f82203dcd2e2be but somehow that hasn't triggered the process to get new images built.

@athomas you mentioned in #97 that:

> the last step of updating the library is still somewhat manual and it appears it didn't happen for the last stable and beta, https://github.com/docker-library/official-images/pull/12541 should catch us up. We'll try to avoid that going forward.

But maybe this one fell through the cracks again?

**Comment by athomas** [comment]
Sort of, this was actually on my todo list today:
https://github.com/docker-library/official-images/pull/17411

@itsjustkevin FYI

**Comment by mnordine** [comment]
Seems like something ripe for automation, and never added to someone's "todo list"?

This issue seems to occur quite frequently, with many Dart devs unable to incorporate latest bug fixes/releases into their CI pipelines.

**Comment by cpswan** [comment]
and again for 3.5.3
