### ISSUE TITLE
Deprecate/discontinue google/dart and dart-lang/dart_docker

### ISSUE THREAD

**Issue by athomas** [dart-lang/dart-docker#23]
With the official images, we should start telling people to migrate from the old images so that we can eventually sunset our use of google/dart and archive the dart-lang/docker_dart (especially because it's easily confused with dart-lang/dart-docker)

Checklist:

  - [x] Update readme: https://github.com/dart-lang/dart-docker/pulls
  - [x] Update readme on https://registry.hub.docker.com/r/google/dart/
  - [x] Update release scripts to no longer publish to this registry when releasing: cl/420720564
  - [x] Anything else on https://registry.hub.docker.com/r/google/dart/ to mark discontinued?
  - [x] Mark https://github.com/dart-lang/dart-docker as Archived
  - [x] Move https://github.com/dart-lang/dart-docker to https://github.com/dart-archive
  - [x] Shutdown infra that is used to publish the docker old images.

**Comment by mit-mit** [comment]
I think we should fix https://github.com/dart-lang/dart-docker/issues/11 first.

**Comment by athomas** [comment]
@mit-mit We don't have arm images on google/dart either.

**Comment by mit-mit** [comment]
Oh, I see. I hadn't internalized that.

**Comment by athomas** [comment]
Accidentally archived this repo instead of dart_docker, undid that.
