### ISSUE TITLE
installing with docker ...  Could not find a file named "pubspec.yaml" in "/app"

### ISSUE THREAD

**Issue by yilmazdurmaz** [dart-lang/dart-docker#28]
I tried to follow docker installation. unfortunately, the given docker content and/or the command to create fails.  the following output should be showing the problem because it is all that is shown.

```
C:\Workspace\dart>docker build -t dart-server .

[+] Building 4.5s (9/14)
 => [internal] load build definition from Dockerfile                                                                                                                                                        0.0s 
 => => transferring dockerfile: 735B                                                                                                                                                                        0.0s 
 => [internal] load .dockerignore                                                                                                                                                                           0.0s 
 => => transferring context: 34B                                                                                                                                                                            0.0s 
 => [internal] load metadata for docker.io/library/dart:stable                                                                                                                                              3.1s 
 => [auth] library/dart:pull token for registry-1.docker.io                                                                                                                                                 0.0s 
 => [build 1/7] FROM docker.io/library/dart:stable@sha256:76d0bf1a79e33bd6e104275aba3d8a1e8479705323ec0e8b00ced40616024c7b                                                                                  0.0s 
 => [internal] load build context                                                                                                                                                                           0.0s 
 => => transferring context: 2B                                                                                                                                                                             0.0s 
 => CACHED [build 2/7] WORKDIR /app                                                                                                                                                                         0.0s 
 => CACHED [build 3/7] COPY pubspec.* ./                                                                                                                                                                    0.0s
 => ERROR [build 4/7] RUN dart pub get                                                                                                                                                                      1.1s
------
 > [build 4/7] RUN dart pub get:
#9 0.892 Could not find a file named "pubspec.yaml" in "/app".
------
executor failed running [/bin/sh -c dart pub get]: exit code: 66

```

**Comment by athomas** [comment]
The guide assumes that you are running this inside a Dart package (as you can see in the guide, even the simplest package requires a pubspec.yaml): https://dart.dev/guides/libraries/create-library-packages

Now, if you're doing this with just a standalone `.dart` script, you'd have to remove the `dart pub get` and anything related to the `pubspec.*` files. But the recommendation would be to just create a pubspec.yaml file.

**Comment by yilmazdurmaz** [comment]
@athomas thanks for answering.

it seems Dart installation documentation assumes too much without expressing those assumptions, causing this kind of problem for newcomers such as me. it is discouraging.

from [https://dart.dev/get-dart](https://dart.dev/get-dart): 

> Installing the Dart SDK
> As the following instructions show, you can use a package manager to easily install and update a stable channel Dart SDK. Alternatively, you can build the SDK from source, grab a Dart Docker image, or install from any release channel by downloading the SDK as a zip file.

so following docker link meets [https://hub.docker.com/_/dart](https://hub.docker.com/_/dart) where there is no further info to dig up.

> Using this image
> We recommend creating small runtime images by leveraging Dart's support for ahead-of-time (AOT) compilation to executables. This enables creating small runtime images (~10 MB).
> The following Dockerfile performs two steps:

and the result is the confusion I got. 

the main "get-dart" page could include a short intro before taking us to docker page, or docker page could have at least a simple link where does this example file belongs, for example, a link to [A simple Dart HTTP server](https://github.com/dart-lang/samples/tree/master/server/simple) like this. or better there could be a simple compile-run dockerfile and it would give much more appreciated start.

many assumptions made without expressing them are just causing loss of appetite.

I now just hope someone includes such simple things in documentation instead of us newcomers trying to dig the web.

**Comment by mit-mit** [comment]
Fixed in https://github.com/docker-library/docs/pull/2062
