### ISSUE TITLE
Terminology for runtime image

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/dart-docker#5]
I find the "scratch" terminology here a bit confusing.

The regular [docker scratch image](https://hub.docker.com/_/scratch) is indeed "scratch" as in "empty".

Could we say something like this?

```
# Create a minimal runtime environment for executing AOT-compiled Dart code
# with the smallest possible image size.
```

**Comment by mit-mit** [comment]
WDYT @subfuzion ?

**Comment by subfuzion** [comment]
I think we were just trying to stress that the image was *almost* a scratch image -- the most minimal possible image you could build based on scratch that only has absolutely essential system files. But I think anything we can do to reduce potential confusion is good.
