### ISSUE TITLE
Add "$HOME/.pub-cache/bin" to the PATH

### ISSUE THREAD

**Issue by Wikiwix** [dart-lang/dart-docker#57]
It would be great if the `"$HOME/.pub-cache/bin"` path would be part of the image's `PATH` variable:

One case this is interesting is for a CI step which installs an executable dart package via `dart pub global activate`.

If the mentioned path would be in `PATH` those executables could be run using their name directly and omitting recompilation on multiple calls.

**Comment by athomas** [comment]
Fixed by dea8edc8a3a22999657392def2cb9135fe996849.
