### ISSUE TITLE
Usage instructions 

### ISSUE THREAD

**Issue by raymondboswel** [dart-lang/dart-docker#64]
HI!

I'm in the process of dockerizing an application that uses dart 2.9.3. To that end I'm trying to use this repository to generate the correct Dockerfile, since the oldest available image is 2.12 (unless I use the deprecated Google images which are 300MB). 

I'm not really well versed in the Dart ecosystem, so I'm having some trouble getting the files in the scripts directory to do what I think they should. 

Any advice would be greatly appreciated, thanks!

**Comment by athomas** [comment]
Sorry, I missed that question.

If I was doing that, I would just modify https://github.com/dart-lang/dart-docker/blob/main/stable/buster/Dockerfile to suit this purpose (replace the version number and SHA checksums with the ones from 2.9.3). The scripts may not work for earlier versions and aren't really meant to be run by users.

If you still want to run them take a look at the github workflows that invoke them:
https://github.com/dart-lang/dart-docker/tree/main/.github/workflows
