### ISSUE TITLE
Documentation on how to bind volume to minimal scatch : AOT  : docker-compose

### ISSUE THREAD

**Issue by redfieldchristabel** [dart-lang/dart-docker#72]
hi there, I'm trying to bind a volume from scratch, from my observation via the official Dockerfile, the location is "/app/bin" for my AOT compiled application. I've built a REST API server and used dart with docker-compose. 

My problem is I cant Bin any volume from what my server creates maybe if someone uploads a picture or even my AOT self-produce file like from "Hive Database". somehow I need to persist it. 

in my docker-compose.yml YAML file, 
I did:
`    volumes:
      - ./user_server:/app/bin
      - hive_path:/app/bin/hive`
 
I also did with: 
`    volumes:
      - ./user_server:/app/bin
`

or even detail as 
`    volumes:
      - ./user_server/hive:/app/bin/hive
      - or
      - - ./user_server:/app/bin/hive
`

nothing work. I tried to create the directory and try not to create the directory.
can you gave some work around?

**Comment by athomas** [comment]
Sorry about the late reply, but this is a general question that should be asked on stackoverflow or a Docker support channel.
