### ISSUE TITLE
pub is unavailable on 2.17

### ISSUE THREAD

**Issue by waghanza** [dart-lang/dart-docker#95]
Hi,

I'm using ` dart:2.17` in https://github.com/the-benchmarker/web-frameworks/pull/5339

I have the following error

```
=> ERROR [4/7] RUN pub get --no-precompile
```

Should I change a PATH or anything ?

Regards,

**Comment by cpswan** [comment]
`pub` as a standalone tool has been [deprecated](https://github.com/dart-lang/sdk/issues/46100), and 2.17 is the release where it's not supported any more. You'll need to change your Dockerfile to use `dart pub`.
