### ISSUE TITLE
Lag between SDK releases and Dart library image updates

### ISSUE THREAD

**Issue by cpswan** [dart-lang/dart-docker#97]
It's been 5 days now since 2.17.1 was released, but the :latest build is still at 2.17.0

`versions.json` here was updated with the 2.17.1 hashes in #94 but somehow that hasn't triggered the (hopefully automated) process to get new images built.

**Comment by cpswan** [comment]
Another week goes by...

I can even see that the images were updated a couple of days ago. But not to use the 2.17.1 SDK.

**Comment by cpswan** [comment]
It seems that https://github.com/docker-library/official-images/blob/master/library/dart hasn't been updated for 2.17.1, and that file is the trigger point for getting new SDKs into the official image.

@athomas and @subfuzion are listed as the maintainers, but it seems that @whesse is regularly the person doing the update (and did the last [PR #12408](https://github.com/docker-library/official-images/pull/12408) to get 2.17.0 done).

**Comment by athomas** [comment]
Thanks for the report, the last step of updating the library is still somewhat manual and it appears it didn't happen for the last stable and beta, https://github.com/docker-library/official-images/pull/12541 should catch us up. We'll try to avoid that going forward.
